config/routes.rb
TestBootstrap::Application.routes.draw do
  get "home/index"

  root :to => "home#index"

  match "/sobre_ligs", :to => "home#about_ligs", :as => "about_ligs"
  match "/templo_central", :to => "home#templo_central", :as => "templo_central"
  match "/ministerio", :to => "home#ministerio", :as => "ministerio"
  match "/encuentros", :to => "home#encuentro", :as => "encuentro"
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@active = "home"
  
  end

  def about_ligs
  	@active = "about_ligs"
  	
  end
  def templo_central
  	@active = "templo_central"
  	
  end
  def ministerio
    @active = "ministerio"
    
  end
  def encuentro
    @active = "encuentro"
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about_ligs.html.haml
:javascript
  function menu(menu_active){
    var array_menu = ["mision", "vision", "historia"];
    for(var i in array_menu){
      if(array_menu[i] == menu_active){
        $('#' + menu_active).fadeIn('slow');
        $('#' + menu_active + '_m').addClass('active');;
      }else{
        $('#' + array_menu[i]).hide();
        $('#' + array_menu[i] + '_m').removeClass('active');
      }
    }
  }
.container-fluid
  .row-fluid
    .span3.well{:style => "margin-top:15px;"}
      %ul.nav.nav-list
        %li.nav-header Sub-Menú
        %li#mision_m.active
          %a{:href => "javascript:menu('mision');"} Misión
        %li#vision_m
          %a{:href => "javascript:menu('vision');"} Visión
        %li#historia_m
          %a{:href => "javascript:menu('historia');"} Historia
    #mision.span9
      %h1 Misión de L.I.G.S. 
      %ul
        %li 1.    Establecemos la casa de oración como espacio de adoración y mover profético.
        %li 2.    Promovemos la intimidad con Dios y la llenura del Espíritu Santo.
        %li 3.    Discipulamos a través de grupos de hogares.
        %li 4.    Formamos bíblicamente líderes integrales para ser influencia.
        %li 5.    Desarrollamos el uso de los talentos y dones espirituales
        %li 6.    Preparamos la iglesia para la segunda venida
      %p{:style => "text-align: justify;"}
        %strong VALORES
      %ul
        %li
          %strong Amor:
          Respeto al prójimo y  una vida de obediencia a sus mandamientos.
        %li
          %strong> Integridad
          \: Hacerlo todo delante de Dios.
        %li
          %strong Excelencia:
          Honrar a Dios, dándole lo mejor.
        %li
          %strong> Servicio
          \: No vinimos a ser servidos sino a servir
    #vision.span9{:style => "display:none;"}
      %h1 Visión de L.I.G.S.
      %p
        Seremos un ministerio que levantará en nuestra nación el nombre de Jesús  atrayendo a las multitudes  a una relación con el Señor, donde serán transformadas y preparadas para servirle.
    #historia.span9{:style => "display:none;"}
      %h1 Historia
      %p{:style => "text-align: justify;"}
        %strong Salmos 2:8… “Pídeme, y  te daré por herencia las naciones, y como posesión tuya los confines de la tierra”.
        %br
          La palabra de Salmos 2:8 es la que marcó el inicio del primer año de LIGS y la que nos ha llevado como iglesia a estar cada día mas sedientos de la presencia y gloria de Dios.
          %br
            %br
              %strong LIGS
              nace en Agosto del año 2010 con el fin de poder
              %strong Levantar un Imperio de Gente Santa
              que pueda aprender a tener una relación intima con el Espíritu Santo y dejarse llevar por los ríos de agua viva que hay para cada miembro de nuestra iglesia, y para todo aquel que quiera vivir experiencias que cambiaran su vida.
              %br
                %br
                  LIGS es sostenidos por el evidente respaldo Divino, sabiendo que los sueños, el llamado y la unción son dados por el Padre, única e inequívocamente, afirmados en principios básicos como el AMOR, la INTEGRIDAD, la EXCELENCIA y el SERVICIO puesto en El.
                  %br
                    %br
                      Convencidos de que Dios tiene grandes planes para esta generación,
                      %strong LIGS
                      sueña con un ministerio que trascienda no sólo las fronteras de nuestra nación, sino también las fronteras denominacionales y espirituales de la Iglesia en el mundo, inspirados en esta promesa que años atrás Dios nos revelara en el libro de
                      %strong Salmos capítulo 2:8
                      ; sin fronteras ni límites en su fé, que sea capaz de penetrar cada espacio de nuestra sociedad, e impactarla con la Palabra de Dios, un ministerio de puertas abiertas, que pueda tender puentes de comunicación con el resto del cuerpo de Cristo, en busca de la unidad de la Iglesia en este tiempo, un ministerio en el cual el único muro que veamos, sea el muro del fuego de Dios, alrededor de su pueblo.

app/views/home/encuentro.html.haml
:javascript
  function menu(menu_active){
    var array_menu = ["1", "2", "3", "4", "5", "6", "7", "8", "9"];
    for(var i in array_menu){
      if(array_menu[i] == menu_active){
        $('#' + menu_active).fadeIn('slow');
        $('#' + menu_active + '_m').addClass('active');;
      }else{
        $('#' + array_menu[i]).hide();
        $('#' + array_menu[i] + '_m').removeClass('active');
      }
    }
  }
.container-fluid
  .row-fluid
    .span3.well{:style => "margin-top:15px;"}
      %ul.nav.nav-list
        %li.nav-header Sub-Menú
        %li#1_m.active
          %a{:href => "javascript:menu('1');"} ¿Qué necesitamos?
        %li#2_m
          %a{:href => "javascript:menu('2');"} ¿Quién necesita un encuentro?
        %li#3_m
          %a{:href => "javascript:menu('3');"} ¿Donde se realiza?
        %li#4_m
          %a{:href => "javascript:menu('4');"} ¿Quién se encarga?
        %li#5_m
          %a{:href => "javascript:menu('5');"} ¿Cuántos día dura?
        %li#6_m
          %a{:href => "javascript:menu('6');"} ¿Cuáles son los requisitos?
        %li#7_m
          %a{:href => "javascript:menu('7');"} ¿Cómo me inscribo?
        %li.divider
        %li#8_m
          %a{:href => "javascript:menu('8');"} Reencuentro
        %li#9_m
          %a{:href => "javascript:menu('9');"} Lugar y fechas de encuentro
    #1.span9
      %h1 ¿Qué Necesitamos?
      %p
        Un corazón dispuesto 
        %strong (Job 11:13). 
        Reconocer nuestra necesidad y ser sensibles a la voz de Dios. El Encuentro como evento no va a cambiar su vida. Lo único que nosotros hacemos es preparar el camino para el Señor 
        %strong (Lucas 3:4-6)
        , crear el ambiente necesario y preparar los corazones, sin embargo el secreto para que su vida sea cambiada es la persona con la que tendrá ese Encuentro: 
        %strong el Señor Jesucristo.
      
    #2.span9{:style => "display:none;"}
      %h1 ¿Quién Necesita un Encuentro?
      %p
        Toda persona que se inicia en los caminos del Señor y/o desee crecer espiritualmente 
        %strong (Hechos 9:9). 
        Después de tres días a solas con Dios, Pablo estaba dispuesto a hacer lo que Dios quería para él. En ese momento, el propósito de Dios fue revelado a su vida, porque Dios sólo pone su visión en un vaso limpio. Lo mismo hace con nosotros cuando en el Encuentro somos confrontados, limpiados, restaurados y renovados.
    #3.span9{:style => "display:none;"}
      %h1 ¿Donde se Realiza el Encuentro?
      %p
        En un lugar retirado de su casa o la iglesia.
    #4.span9{:style => "display:none;"}
      %h1 ¿Quién se Encarga de Realizar el Evento?
      %p
        Hay un equipo de trabajo, conformado por:
      %ul

        %li Pastores: Encargados de la organización, desarrollo y supervisión del Encuentro.
        %li Líderes de Encuentro: Encargados de la logística en el lugar escogido y responsables del funcionamiento de acuerdo con lo establecido.
        %li Guías de Encuentro :Soportes de líderes de Encuentro en todo el desarrollo del evento.
    #5.span9{:style => "display:none;"}
      %h1 ¿Cuantos Días Dura?
      %p
        Se realiza en un fin de semana. Empieza el viernes en la noche, continúa el sábado en el sitio establecido e incluye el hospedaje de esas dos noches. Finaliza el domingo en la tarde.
    #6.span9{:style => "display:none;"}
      %h1 ¿Cuales son los Requisitos?

      %ol{:type => "1"}
        %li Estar asistiendo a un Grupo de hogar.
        %li Recibir, de parte del líder o de la persona delegada por el mismo, la enseñanza de los Pre-Encuentro. 
        %li Haber cancelado el valor del Encuentro.
    #7.span9{:style => "display:none;"}
      %h1 ¿Como me Inscribo?
      %p Comuníquese con su Líder o Encargado de grupo. Él le brindara la información sobre forma de pago e inscripción.
    #8.span9{:style => "display:none;"}
      %h1 ¿Donde se Realiza el Encuentro?
      %p
        En un lugar retirado de su casa o la iglesia.
    #9.span9{:style => "display:none;"}
      %h1 ¿Donde se Realiza el Encuentro?
      %p
        En un lugar retirado de su casa o la iglesia.

app/views/home/index.html.haml
.container-fluid
  .row-fluid
    .span3.well
      %ul.nav.nav-list
        %li.nav-header List header
        %li.active
          %a{:href => "#"} Home
        %li
          %a{:href => "#"} Library
        %li
          %a{:href => "#"} Applications
        %li.nav-header Another list header
        %li
          %a{:href => "#"} Profile
        %li
          %a{:href => "#"} Settings
        %li.divider
        %li
          %a{:href => "#"} Help
    .span9{:style => "background-color:red;height:300px;"}

app/views/home/templo_central.html.haml
:javascript
  function menu(menu_active){
    var array_menu = ["dateday", "grouphouse"];
    for(var i in array_menu){
      if(array_menu[i] == menu_active){
        $('#' + menu_active).fadeIn('slow');
        $('#' + menu_active + '_m').addClass('active');;
      }else{
        $('#' + array_menu[i]).hide();
        $('#' + array_menu[i] + '_m').removeClass('active');
      }
    }
  }
.container-fluid
  .row-fluid
    .span3.well{:style => "margin-top:15px;"}
      %ul.nav.nav-list
        %li.nav-header Sub-Menú
        %li#dateday_m.active
          %a{:href => "javascript:menu('dateday');"} Días de Reuniones
        %li#grouphouse_m
          %a{:href => "javascript:menu('grouphouse');"} Grupos de Hogar
    #dateday.span9
      %h1 Días de Reuniones 
      %p
        Nuestros cultos de avivamiento, sanidades, adoración y alabanza. Se realizan todos los domingos en el templo central ubicado en Avda. Américo Vespucio Sur 0292, La Cisterna. (Metro Estación La Cisterna).
      %p
        %strong Horario: Domingos a partir de las 18:30 hrs
      %p
        %strong Días de Oración:
      %p
        Miércoles a las 20:00 hrs en Templo Central ubicado en Avda. Américo Vespucio Sur 0292, La Cisterna. (Metro Estación La Cisterna).
        Martes a las 20:00 hrs en sector norte de Santiago, Comuna de Quilicura. (Contactar a contacto@ligs.cl).
      %img{:alt => "Ubicación de LIGS", :border => "0", :src => "assets/mapa_ligs.jpg"}/
    #grouphouse.span9
      %h1 Grupos de Hogar 
      %p
        El eje principal de la iglesia y el punto de partida de todo el proceso de formación, tanto para las personas nuevas como para cristianos que quieran estar plantados en la iglesia, son los “Grupos de Hogar”. El propósito del Grupo de Hogar es tener un lugar en donde las personas se conecten a la iglesia, se relacionen con otros, sean formadas, puedan servir, y puedan disfrutar de los beneficios que la iglesia ofrece a quienes están plantados.

app/views/layouts/application.html.haml
<!doctype html>
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
    %title TestBootstrap
    = stylesheet_link_tag    "bootstrap.min" 
    = stylesheet_link_tag    "bootstrap-responsive.min" 
    = stylesheet_link_tag    "font-awesome.min" 
    
    = csrf_meta_tags 
%body{:style => "background-image: url('/assets/gplaypattern.png');background-position: initial initial; background-repeat: initial initial;"}
  / .navbar.navbar-fixed-top.navbar-static-top
  /   .navbar-inner
  /     %a.brand{:href => "#"}
  /       #logo-titulo{:style => "margin-left:10px;"}
  /         L.I.G.S.
  /     %ul.nav
  /       %li.divider-vertical
  /       %li.active
  /         %a{:href => "#"} Home
  /       %li.divider-vertical
  /       %li
  /         %a{:href => "#"} Link
  /       %li.divider-vertical
  /       %li
  /         %a{:href => "#"} Link
  /       %li.divider-vertical
  /       %li
  /         %a{:href => "#"} Link
  /       %li.divider-vertical
  /       %form.navbar-search.pull-left
  /         %input.search-query{:type => "text", :placeholder => "Search"}
  .navbar.navbar-fixed-top.navbar-static-top
    .navbar-inner
      .container
        %a.btn.btn-navbar{"data-target" => ".navbar-responsive-collapse", "data-toggle" => "collapse"}
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.brand{:href => "#{root_path}"} L.I.G.S.
        .nav-collapse.collapse.navbar-responsive-collapse
          %ul.nav
            %li#home
              %a{:href => "#{root_path}"} 
                %i.icon-home
                Home
            %li#about_ligs
              %a{:href => "#{about_ligs_path}"} 
                %i.icon-bullhorn
                Sobre L.I.G.S
            %li#templo_central
              %a{:href => "#{templo_central_path}"} 
                %i.icon-road
                Templo Central
            %li#ministerio
              %a{:href => "#{ministerio_path}"} 
                %i.icon-briefcase
                Ministerios
            %li#encuentro
              %a{:href => "#{encuentro_path}"} 
                %i.icon-retweet
                Encuentros
            %li
              %a{:href => "#"} 
                %i.icon-picture
                Medios
            %li
              %a{:href => "#"} 
                %i.icon-book
                Cursos de Formación
            %li
              %a{:href => "#"} 
                %i.icon-envelope
                Contacto

  / %header#overview.jumbotron.subhead{:style => "margin-top:40px;background-image: url('/assets/debut_light.png');background-position: initial initial; background-repeat: initial initial;border-bottom:1px solid #B1B1B1;margin-bottom:5px;"}
  /   .container
  /     %br
  /     %br
  /     %br
  /     .row
  /       .span6
  /         %h1 L.I.G.S.
  /         %p.lead Levantando un Imperio de Gente Santa.
  /       .span6
  /         %i.icon-desktop{:style => "font-size:100px;"}
  /         %i.icon-laptop.icon-4x
  /         %i.icon-tablet.icon-4x
  /         %i.icon-mobile-phone.icon-4x
  /     %br
  /     %br
  /     %br
  #myCarousel.carousel.slide{:style => "margin-top:40px"}
    .carousel-inner
      .item.active
        %img{:alt => "", :src => "assets/3.png"}
          .carousel-caption
            %p.lead Levantando un Imperio de Gente Santa.
      .item
        %img{:alt => "", :src => "assets/3.png"}
          .carousel-caption
            %p.lead Levantando un Imperio de Gente Santa.
      .item
        %img{:alt => "", :src => "assets/3.png"}
          .carousel-caption
            %p.lead Levantando un Imperio de Gente Santa.
    %a.left.carousel-control{"data-slide" => "prev", :href => "#myCarousel"} ‹
    %a.right.carousel-control{"data-slide" => "next", :href => "#myCarousel"} ›
  .container-fluid{:style => "border-top:1px solid #B1B1B1"}
    .row-fluid{:style => "margin-top:5px;"}
      .span8.offset2
        = yield
      / .span2{:style => "background-image: url('/assets/grey.png');background-position: initial initial; background-repeat: initial initial;height:400px;"}
      /   .btn-group
      /     %a.btn.btn-primary{:href => "#"}
      /       %i.icon-user.icon-white
      /       User
      /     %a.btn.btn-primary.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
      /       %span.caret
      /     %ul.dropdown-menu
      /       %li
      /         %a{:href => "#"}
      /           %i.icon-pencil
      /           Edit
      /       %li
      /         %a{:href => "#"}
      /           %i.icon-trash
      /           Delete
      /       %li
      /         %a{:href => "#"}
      /           %i.icon-ban-circle
      /           Ban
      /       %li.divider
      /       %li
      /         %a{:href => "#"}
      /           %i.i
      /           Make admin
#footer{:style => "background-color: #f5f5f5;margin-top:100px;border:1px solid #b1b1b1"}
  .container
    .row
      .span6.offset3{:style => "font-size: 12px;text-align:center;"}
        %p
          L.I.G.S. | Levantando un Imperio de Gente Santa © www.ligs.cl
          %br
          Templo Central ubicado en Avda. Américo Vespucio Sur 0292, La Cisterna. (Metro Estación La Cisterna)
          %br
          Personalidad Jurídica 2424
          %br
          Email: contacto@ligs.cl
  = javascript_include_tag "jquery" 
  = javascript_include_tag "application" 
  = javascript_include_tag "bootstrap-transition"
  = javascript_include_tag "bootstrap-alert"
  = javascript_include_tag "bootstrap-modal"
  = javascript_include_tag "bootstrap-dropdown"
  = javascript_include_tag "bootstrap-scrollspy"
  = javascript_include_tag "bootstrap-tab"
  = javascript_include_tag "bootstrap-tooltip"
  = javascript_include_tag "bootstrap-popover"
  = javascript_include_tag "bootstrap-button"
  = javascript_include_tag "bootstrap-collapse"
  = javascript_include_tag "bootstrap-carousel"
  = javascript_include_tag "bootstrap-typeahead"
  = javascript_include_tag "bootstrap-affix"
  - if @active
    :javascript
      $("##{@active}").addClass('active');